---
title: "In Class Ex 01"

author: "Cheng Chun Chieh"

date: "13 Apr 2024"
date-modified: "last-modified"

format: html
execute: 
  echo: true
  eval: true
  warning: false
  freeze: true
  
editor: visual
---

# In Class Ex 01

## 1.1 Loading the required packages

```{r}
pacman::p_load(tidyverse)
```

## 1.2 Loading the data

Rmb to use read_csv instead or read.csv

Using read_csv will retain the field names as per the csv file.

```{r}
realis2019 <- read_csv("data/realis2019.csv")
```

## 2.1 Some Visualisation

First - to take a look at the data:

```{r}
head(realis2019)
```

```{r}
colnames(realis2019)
```

```{r}

realis2019 <- realis2019 %>% 
  rename(
    unit_psm = 'Unit Price ($ psm)',
    unit_psf = 'Unit Price ($ psf)',
    sale_date = 'Sale Date',
    property_type = `Property Type`,
    sale_type = `Type of Sale`,
    planning_region = `Planning Region`,
    planning_area = `Planning Area`,
    trans_price = `Transacted Price ($)`
      )
```

Checking the transaction price across planning regions:

```{r}
ggplot(data=realis2019, 
       aes(x= trans_price)) +
  geom_histogram(bins=50) +
  xlim (0, 5000000) +
  facet_wrap(~ planning_region) +
  labs(title="Histogram of Transacted Price across Planning Regions (up to $5M)", y="Count", x="Transacted Price ($)")+
  theme_minimal() +
  theme(axis.text.x = element_text(size = 6))
```

```{r}

ggplot(data=realis2019, 
       aes(x= unit_psm)) +
  geom_histogram(bins=50) +
  labs(title="Histogram of Unit Price (psf)", y="Count", x="Transacted Price ($)") +
  theme_minimal()

```

```{r}
ggplot(data=realis2019, 
       aes(x= unit_psm)) +
  geom_histogram(bins=50) +
  facet_wrap(~ planning_region) +
  labs(title="Histogram of Unit Price (psf) across Planning Regions", y="Count", x="Transacted Price ($)")+
  theme_minimal() +
  theme(axis.text.x = element_text(size = 8))
```

Taking a look at the unit price (psf) across property types:

```{r}

ggplot(data=realis2019, 
       aes(y = unit_psf, x= property_type)) +
  geom_boxplot(colour ="black", fill="#88abff", alpha=0.5) +
  geom_point(stat="summary",        
             fun=mean,           
             colour ="darkblue",          
             size=2) +
  theme_light() +
  labs(title="Unit Price (psf) across Property Type", y="Unit Price ($psf)", x="Property Type")
```

and across planning regions:

```{r}

ggplot(data=realis2019, 
       aes(y = unit_psf, x= planning_region)) +
  geom_boxplot(colour ="black", fill="#88abff", alpha=0.5) +
  geom_point(stat="summary",        
             fun=mean,           
             colour ="darkblue",          
             size=2) +
  theme_light() +
  labs(title="Unit Price (psf) across Planning Region", y="Unit Price ($psf)", x="Planning Region")
```
